#!/usr/bin/env node
/**
 * Read each rule's meta.docs.category + meta.docs.recommended and emit:
 *
 *   src/configs/recommended.ts      (legacy .eslintrc shape)
 *   src/configs/strict.ts
 *   src/configs/migration.ts
 *   src/configs/flat-recommended.ts (ESLint 9+ flat config shape)
 *   src/configs/flat-strict.ts
 *   src/configs/flat-migration.ts
 *
 * Runs in `prebuild` so the configs always match the live rule registry.
 * Don't hand-edit the generated files — they're recomputed every build.
 */

import { execSync } from 'node:child_process'
import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')
const CONFIGS_DIR = resolve(ROOT, 'src/configs')

mkdirSync(CONFIGS_DIR, { recursive: true })

// Use the TS compiler API via `tsx` would be cleaner, but cheaper: compile rules
// to JS via tsc to a temp dir, then import. Simplest path: spawn `tsx` to load
// the rules module directly.
const rulesModule = await import(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  /** @type any */ ('../src/rules/index.ts')
).catch(async () => {
  // Fallback: compile + import. tsx is preferred but not strictly required.
  console.error(
    '[generate-configs] Direct import of src/rules/index.ts failed. ' +
      'Install `tsx` or run `pnpm tsx scripts/generate-configs.mjs`.',
  )
  process.exit(1)
})

const { rules } = rulesModule

const PLUGIN_NAME = 'shilp-sutra'

/**
 * Group rules by category. Each rule's meta.docs.category determines preset
 * membership; meta.docs.recommended determines the severity in `recommended`.
 */
const categorized = { recommended: [], strict: [], migration: [] }
for (const [name, rule] of Object.entries(rules)) {
  const cat = rule.meta?.docs?.category
  const recommended = rule.meta?.docs?.recommended
  if (cat === 'migration') {
    categorized.migration.push([name, recommended ?? 'error'])
    categorized.strict.push([name, 'error'])
  } else if (cat === 'recommended') {
    categorized.recommended.push([name, recommended ?? 'warn'])
    categorized.strict.push([name, 'error'])
  } else if (cat === 'stylistic') {
    categorized.strict.push([name, recommended ?? 'warn'])
  }
}

function legacyConfig(rulesList) {
  const lines = rulesList
    .map(([name, severity]) => `    '${PLUGIN_NAME}/${name}': '${severity}',`)
    .join('\n')
  return `// Generated by scripts/generate-configs.mjs — do not edit.
const config = {
  plugins: ['${PLUGIN_NAME}'],
  rules: {
${lines}
  },
}

export default config
`
}

function flatConfig(rulesList) {
  const lines = rulesList
    .map(([name, severity]) => `    '${PLUGIN_NAME}/${name}': '${severity}',`)
    .join('\n')
  return `// Generated by scripts/generate-configs.mjs — do not edit.
import { plugin } from '../index'

const config = {
  plugins: { '${PLUGIN_NAME}': plugin },
  rules: {
${lines}
  },
}

export default config
`
}

const targets = [
  ['recommended.ts', legacyConfig(categorized.recommended)],
  ['strict.ts', legacyConfig(categorized.strict)],
  ['migration.ts', legacyConfig(categorized.migration)],
  ['flat-recommended.ts', flatConfig(categorized.recommended)],
  ['flat-strict.ts', flatConfig(categorized.strict)],
  ['flat-migration.ts', flatConfig(categorized.migration)],
]

for (const [filename, content] of targets) {
  writeFileSync(resolve(CONFIGS_DIR, filename), content)
}

console.log(
  `[generate-configs] wrote ${targets.length} config files (recommended: ${categorized.recommended.length}, strict: ${categorized.strict.length}, migration: ${categorized.migration.length} rules)`,
)
