/**
 * Vite-level stub for @tabler/icons-react.
 *
 * Aliased in vitest.config.ts so Vite never resolves the real
 * @tabler/icons-react barrel which re-exports ~12,010 icon files.
 * Each icon becomes a trivial forwardRef SVG component.
 */
import React from 'react'

type IconProps = React.SVGAttributes<SVGSVGElement> & {
  size?: number | string
  stroke?: number | string
}

/** Convert PascalCase icon name to kebab class: IconArrowUp → arrow-up */
function toKebab(name: string): string {
  return name
    .replace(/^Icon/, '')
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .toLowerCase()
}

/** Stub icon factory — renders a 24×24 <svg> with tabler-icon classes + data-icon. */
function makeIcon(name: string) {
  const kebab = toKebab(name)
  const Icon = React.forwardRef<SVGSVGElement, IconProps>(
    ({ size = 24, stroke: _stroke, children: _children, className, ...props }, ref) =>
      React.createElement('svg', {
        ref,
        width: size,
        height: size,
        viewBox: '0 0 24 24',
        'data-icon': name,
        className: [
          'tabler-icon',
          `tabler-icon-${kebab}`,
          className,
        ].filter(Boolean).join(' '),
        ...props,
      }),
  )
  Icon.displayName = name
  return Icon
}

// ── Type export ──────────────────────────────────────────────────────────────
export type Icon = React.ForwardRefExoticComponent<IconProps & React.RefAttributes<SVGSVGElement>>

// ── Icon exports (all icons used in karm + core UI/composed/shell) ───────────
// Generated by: grep -roh 'Icon[A-Z][A-Za-z0-9]*' packages/{karm,core}/src | sort -u
export const IconActivity = makeIcon('IconActivity')
export const IconAdjustmentsHorizontal = makeIcon('IconAdjustmentsHorizontal')
export const IconAlertCircle = makeIcon('IconAlertCircle')
export const IconAlertTriangle = makeIcon('IconAlertTriangle')
export const IconAlertTriangleFilled = makeIcon('IconAlertTriangleFilled')
export const IconAlignCenter = makeIcon('IconAlignCenter')
export const IconAlignLeft = makeIcon('IconAlignLeft')
export const IconAlignRight = makeIcon('IconAlignRight')
export const IconArchive = makeIcon('IconArchive')
export const IconArrowBackUp = makeIcon('IconArrowBackUp')
export const IconArrowBarRight = makeIcon('IconArrowBarRight')
export const IconArrowBarToRight = makeIcon('IconArrowBarToRight')
export const IconArrowDown = makeIcon('IconArrowDown')
export const IconArrowForward = makeIcon('IconArrowForward')
export const IconArrowForwardUp = makeIcon('IconArrowForwardUp')
export const IconArrowLeft = makeIcon('IconArrowLeft')
export const IconArrowRight = makeIcon('IconArrowRight')
export const IconArrowsMaximize = makeIcon('IconArrowsMaximize')
export const IconArrowsShuffle = makeIcon('IconArrowsShuffle')
export const IconArrowsSort = makeIcon('IconArrowsSort')
export const IconArrowUp = makeIcon('IconArrowUp')
export const IconBan = makeIcon('IconBan')
export const IconBell = makeIcon('IconBell')
export const IconBlockquote = makeIcon('IconBlockquote')
export const IconBold = makeIcon('IconBold')
export const IconBolt = makeIcon('IconBolt')
export const IconBook = makeIcon('IconBook')
export const IconBriefcase = makeIcon('IconBriefcase')
export const IconCalendar = makeIcon('IconCalendar')
export const IconCalendarCheck = makeIcon('IconCalendarCheck')
export const IconCalendarClock = makeIcon('IconCalendarClock')
export const IconCalendarEvent = makeIcon('IconCalendarEvent')
export const IconChartBar = makeIcon('IconChartBar')
export const IconCheck = makeIcon('IconCheck')
export const IconChecks = makeIcon('IconChecks')
export const IconChevronDown = makeIcon('IconChevronDown')
export const IconChevronLeft = makeIcon('IconChevronLeft')
export const IconChevronRight = makeIcon('IconChevronRight')
export const IconChevronUp = makeIcon('IconChevronUp')
export const IconCircle = makeIcon('IconCircle')
export const IconCircleCheck = makeIcon('IconCircleCheck')
export const IconCircleX = makeIcon('IconCircleX')
export const IconClipboard = makeIcon('IconClipboard')
export const IconClipboardList = makeIcon('IconClipboardList')
export const IconClock = makeIcon('IconClock')
export const IconCode = makeIcon('IconCode')
export const IconCoffee = makeIcon('IconCoffee')
export const IconColumns = makeIcon('IconColumns')
export const IconColumns3 = makeIcon('IconColumns3')
export const IconCopy = makeIcon('IconCopy')
export const IconCornerDownLeft = makeIcon('IconCornerDownLeft')
export const IconCurrencyDollar = makeIcon('IconCurrencyDollar')
export const IconDots = makeIcon('IconDots')
export const IconDotsVertical = makeIcon('IconDotsVertical')
export const IconDownload = makeIcon('IconDownload')
export const IconEdit = makeIcon('IconEdit')
export const IconExternalLink = makeIcon('IconExternalLink')
export const IconEye = makeIcon('IconEye')
export const IconEyeOff = makeIcon('IconEyeOff')
export const IconFile = makeIcon('IconFile')
export const IconFileCode = makeIcon('IconFileCode')
export const IconFileSpreadsheet = makeIcon('IconFileSpreadsheet')
export const IconFileText = makeIcon('IconFileText')
export const IconFileUnknown = makeIcon('IconFileUnknown')
export const IconFileZip = makeIcon('IconFileZip')
export const IconFilter = makeIcon('IconFilter')
export const IconFilterX = makeIcon('IconFilterX')
export const IconFlag = makeIcon('IconFlag')
export const IconFlame = makeIcon('IconFlame')
export const IconFolder = makeIcon('IconFolder')
export const IconFolderOpen = makeIcon('IconFolderOpen')
export const IconGauge = makeIcon('IconGauge')
export const IconGitBranch = makeIcon('IconGitBranch')
export const IconGitCommit = makeIcon('IconGitCommit')
export const IconGitPullRequest = makeIcon('IconGitPullRequest')
export const IconGripVertical = makeIcon('IconGripVertical')
export const IconH2 = makeIcon('IconH2')
export const IconH3 = makeIcon('IconH3')
export const IconHeart = makeIcon('IconHeart')
export const IconHighlight = makeIcon('IconHighlight')
export const IconHistory = makeIcon('IconHistory')
export const IconInbox = makeIcon('IconInbox')
export const IconInfoCircle = makeIcon('IconInfoCircle')
export const IconItalic = makeIcon('IconItalic')
export const IconKeyboard = makeIcon('IconKeyboard')
export const IconLanguage = makeIcon('IconLanguage')
export const IconLayoutDashboard = makeIcon('IconLayoutDashboard')
export const IconLayoutGrid = makeIcon('IconLayoutGrid')
export const IconLayoutKanban = makeIcon('IconLayoutKanban')
export const IconLayoutList = makeIcon('IconLayoutList')
export const IconLayoutSidebarLeftCollapse = makeIcon('IconLayoutSidebarLeftCollapse')
export const IconLineDashed = makeIcon('IconLineDashed')
export const IconLink = makeIcon('IconLink')
export const IconList = makeIcon('IconList')
export const IconListCheck = makeIcon('IconListCheck')
export const IconListNumbers = makeIcon('IconListNumbers')
export const IconLoader2 = makeIcon('IconLoader2')
export const IconLock = makeIcon('IconLock')
export const IconLogout = makeIcon('IconLogout')
export const IconMail = makeIcon('IconMail')
export const IconMaximize = makeIcon('IconMaximize')
export const IconMenu2 = makeIcon('IconMenu2')
export const IconMessage = makeIcon('IconMessage')
export const IconMessageCircle = makeIcon('IconMessageCircle')
export const IconMessagePlus = makeIcon('IconMessagePlus')
export const IconMinimize = makeIcon('IconMinimize')
export const IconMinus = makeIcon('IconMinus')
export const IconMoodSmile = makeIcon('IconMoodSmile')
export const IconMoon = makeIcon('IconMoon')
export const IconNews = makeIcon('IconNews')
export const IconPackage = makeIcon('IconPackage')
export const IconPaperclip = makeIcon('IconPaperclip')
export const IconPencil = makeIcon('IconPencil')
export const IconPhoto = makeIcon('IconPhoto')
export const IconPinnedFilled = makeIcon('IconPinnedFilled')
export const IconPlayerPause = makeIcon('IconPlayerPause')
export const IconPlayerPlay = makeIcon('IconPlayerPlay')
export const IconPlus = makeIcon('IconPlus')
export const IconRefresh = makeIcon('IconRefresh')
export const IconRobot = makeIcon('IconRobot')
export const IconRocket = makeIcon('IconRocket')
export const IconSearch = makeIcon('IconSearch')
export const IconSend = makeIcon('IconSend')
export const IconServerOff = makeIcon('IconServerOff')
export const IconSettings = makeIcon('IconSettings')
export const IconShare = makeIcon('IconShare')
export const IconShieldCheck = makeIcon('IconShieldCheck')
export const IconSparkles = makeIcon('IconSparkles')
export const IconSquare = makeIcon('IconSquare')
export const IconSquareCheck = makeIcon('IconSquareCheck')
export const IconStar = makeIcon('IconStar')
export const IconStarFilled = makeIcon('IconStarFilled')
export const IconStrikethrough = makeIcon('IconStrikethrough')
export const IconSubtask = makeIcon('IconSubtask')
export const IconSun = makeIcon('IconSun')
export const IconTag = makeIcon('IconTag')
export const IconTextResize = makeIcon('IconTextResize')
export const IconTrash = makeIcon('IconTrash')
export const IconTrendingDown = makeIcon('IconTrendingDown')
export const IconTrendingUp = makeIcon('IconTrendingUp')
export const IconUmbrella = makeIcon('IconUmbrella')
export const IconUnderline = makeIcon('IconUnderline')
export const IconUpload = makeIcon('IconUpload')
export const IconUser = makeIcon('IconUser')
export const IconUserCircle = makeIcon('IconUserCircle')
export const IconUserMinus = makeIcon('IconUserMinus')
export const IconUserPlus = makeIcon('IconUserPlus')
export const IconUsers = makeIcon('IconUsers')
export const IconVideo = makeIcon('IconVideo')
export const IconVolume = makeIcon('IconVolume')
export const IconVolumeOff = makeIcon('IconVolumeOff')
export const IconWorld = makeIcon('IconWorld')
export const IconX = makeIcon('IconX')
export const IconZoomIn = makeIcon('IconZoomIn')
export const IconZoomOut = makeIcon('IconZoomOut')
export const IconZoomReset = makeIcon('IconZoomReset')
