import type { Config } from 'tailwindcss'

const preset: Partial<Config> = {
  /**
   * Dark mode uses the `.dark` class strategy. If your app uses `darkMode: 'media'`,
   * set it explicitly in your own tailwind.config — your config takes precedence.
   */
  darkMode: 'class',
  theme: {
    extend: {
      // Breakpoints must be static values — CSS custom properties cannot be used
      // in @media queries (compiled at build time). These mirror the tokens in
      // semantic.css (--breakpoint-sm … --breakpoint-2xl).
      // Placed inside `extend` so deployer breakpoints are merged, not replaced.
      screens: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1536px',
      },
      fontFamily: {
        sans: ['var(--font-sans)', 'system-ui', 'sans-serif'],
        display: ['var(--font-display)', 'system-ui', 'sans-serif'],
        body: ['var(--font-body)', 'sans-serif'],
        accent: ['var(--font-accent)', 'sans-serif'],
        mono: ['var(--font-mono)', 'monospace'],
      },
      fontWeight: {
        light: 'var(--font-weight-light)',
        regular: 'var(--font-weight-regular)',
        medium: 'var(--font-weight-medium)',
        semibold: 'var(--font-weight-semibold)',
        bold: 'var(--font-weight-bold)',
      },
      letterSpacing: {
        'ds-tighter': 'var(--tracking-tighter)',
        'ds-tight': 'var(--tracking-tight)',
        'ds-normal': 'var(--tracking-normal)',
        'ds-wide': 'var(--tracking-wide)',
        'ds-wider': 'var(--tracking-wider)',
        'ds-widest': 'var(--tracking-widest)',
      },
      lineHeight: {
        'ds-none': 'var(--line-height-none)',
        'ds-tight': 'var(--line-height-tight)',
        'ds-snug': 'var(--line-height-snug)',
        'ds-normal': 'var(--line-height-normal)',
        'ds-relaxed': 'var(--line-height-relaxed)',
        'ds-loose': 'var(--line-height-loose)',
      },
      fontSize: {
        'ds-xs':   ['var(--font-size-xs)',   { lineHeight: 'var(--line-height-relaxed)' }],
        'ds-sm':   ['var(--font-size-sm)',   { lineHeight: 'var(--line-height-relaxed)' }],
        'ds-md':   ['var(--font-size-md)',   { lineHeight: 'var(--line-height-relaxed)' }],
        'ds-base': ['var(--font-size-base)', { lineHeight: 'var(--line-height-relaxed)' }],
        'ds-lg':   ['var(--font-size-lg)',   { lineHeight: 'var(--line-height-normal)' }],
        'ds-xl':   ['var(--font-size-xl)',   { lineHeight: 'var(--line-height-snug)' }],
        'ds-2xl':  ['var(--font-size-2xl)',  { lineHeight: 'var(--line-height-snug)' }],
        'ds-3xl':  ['var(--font-size-3xl)',  { lineHeight: 'var(--line-height-tight)' }],
        'ds-4xl':  ['var(--font-size-4xl)',  { lineHeight: 'var(--line-height-tight)' }],
        'ds-5xl':  ['var(--font-size-5xl)',  { lineHeight: 'var(--line-height-tight)' }],
        'ds-6xl':  ['var(--font-size-6xl)',  { lineHeight: 'var(--line-height-tight)' }],
      },
      borderWidth: {
        'ds-sm': 'var(--border-width-sm)',
        'ds-md': 'var(--border-width-md)',
        'ds-lg': 'var(--border-width-lg)',
        'focus': 'var(--border-focus-width)',
      },
      borderRadius: {
        'ds-none': '0',
        'ds-sm': 'var(--radius-sm)',
        'ds-default': 'var(--radius-default)',
        'ds-md': 'var(--radius-md)',
        'ds-lg': 'var(--radius-lg)',
        'ds-xl': 'var(--radius-xl)',
        'ds-2xl': 'var(--radius-2xl)',
        'ds-full': 'var(--radius-full)',
      },
      spacing: {
        'ds-01': 'var(--spacing-01)',
        'ds-02': 'var(--spacing-02)',
        'ds-02b': 'var(--spacing-02b)',
        'ds-03': 'var(--spacing-03)',
        'ds-04': 'var(--spacing-04)',
        'ds-05': 'var(--spacing-05)',
        'ds-05b': 'var(--spacing-05b)',
        'ds-06': 'var(--spacing-06)',
        'ds-06b': 'var(--spacing-06b)',
        'ds-07': 'var(--spacing-07)',
        'ds-08': 'var(--spacing-08)',
        'ds-09': 'var(--spacing-09)',
        'ds-10': 'var(--spacing-10)',
        'ds-11': 'var(--spacing-11)',
        'ds-12': 'var(--spacing-12)',
        'ds-13': 'var(--spacing-13)',
      },
      width: {
        'ds-xs': 'var(--size-xs)',
        'ds-xs-plus': 'var(--size-xs-plus)',
        'ds-sm': 'var(--size-sm)',
        'ds-sm-plus': 'var(--size-sm-plus)',
        'ds-md': 'var(--size-md)',
        'ds-lg': 'var(--size-lg)',
        'ds-xl': 'var(--size-xl)',
        'ico-sm': 'var(--icon-sm)',
        'ico-md': 'var(--icon-md)',
        'ico-lg': 'var(--icon-lg)',
        'ico-xl': 'var(--icon-xl)',
      },
      height: {
        'ds-xs': 'var(--size-xs)',
        'ds-xs-plus': 'var(--size-xs-plus)',
        'ds-sm': 'var(--size-sm)',
        'ds-sm-plus': 'var(--size-sm-plus)',
        'ds-md': 'var(--size-md)',
        'ds-lg': 'var(--size-lg)',
        'ds-xl': 'var(--size-xl)',
        'ico-sm': 'var(--icon-sm)',
        'ico-md': 'var(--icon-md)',
        'ico-lg': 'var(--icon-lg)',
        'ico-xl': 'var(--icon-xl)',
      },
      minHeight: {
        'ds-xs': 'var(--size-xs)',
        'ds-xs-plus': 'var(--size-xs-plus)',
        'ds-sm': 'var(--size-sm)',
        'ds-sm-plus': 'var(--size-sm-plus)',
        'ds-md': 'var(--size-md)',
        'ds-lg': 'var(--size-lg)',
        'ds-xl': 'var(--size-xl)',
      },
      maxWidth: {
        layout: 'var(--max-width)',
        'layout-body': 'var(--max-width-body)',
      },
      minWidth: {
        'ds-xs': 'var(--size-xs)',
        'ds-sm': 'var(--size-sm)',
        'ds-md': 'var(--size-md)',
        'ds-lg': 'var(--size-lg)',
        'ds-xl': 'var(--size-xl)',
      },
      opacity: {
        'action-hover': 'var(--action-hover-opacity)',
        'action-selected': 'var(--action-selected-opacity)',
        'action-disabled': 'var(--action-disabled-opacity)',
        'action-focus': 'var(--action-focus-opacity)',
        'action-active': 'var(--action-active-opacity)',
      },
      colors: {
        // ═══ NEW: 12-step accent scale ═══
        'accent-1': 'var(--color-accent-1)',
        'accent-2': 'var(--color-accent-2)',
        'accent-3': 'var(--color-accent-3)',
        'accent-4': 'var(--color-accent-4)',
        'accent-5': 'var(--color-accent-5)',
        'accent-6': 'var(--color-accent-6)',
        'accent-7': 'var(--color-accent-7)',
        'accent-8': 'var(--color-accent-8)',
        'accent-9': 'var(--color-accent-9)',
        'accent-10': 'var(--color-accent-10)',
        'accent-11': 'var(--color-accent-11)',
        'accent-12': 'var(--color-accent-12)',
        'accent-fg': 'var(--color-accent-fg)',

        // ═══ NEW: 12-step secondary scale ═══
        'secondary-1': 'var(--color-secondary-1)',
        'secondary-2': 'var(--color-secondary-2)',
        'secondary-3': 'var(--color-secondary-3)',
        'secondary-4': 'var(--color-secondary-4)',
        'secondary-5': 'var(--color-secondary-5)',
        'secondary-6': 'var(--color-secondary-6)',
        'secondary-7': 'var(--color-secondary-7)',
        'secondary-8': 'var(--color-secondary-8)',
        'secondary-9': 'var(--color-secondary-9)',
        'secondary-10': 'var(--color-secondary-10)',
        'secondary-11': 'var(--color-secondary-11)',
        'secondary-12': 'var(--color-secondary-12)',
        'secondary-fg': 'var(--color-secondary-fg)',

        // ═══ NEW: Surface ═══
        'surface-1': 'var(--color-surface-1)',
        'surface-2': 'var(--color-surface-2)',
        'surface-3': 'var(--color-surface-3)',
        'surface-4': 'var(--color-surface-4)',
        'surface-fg': 'var(--color-surface-fg)',
        'surface-fg-muted': 'var(--color-surface-fg-muted)',
        'surface-fg-subtle': 'var(--color-surface-fg-subtle)',
        'surface-border': 'var(--color-surface-border)',
        'surface-border-strong': 'var(--color-surface-border-strong)',

        // ═══ NEW: Status (step subsets) ═══
        'error-3': 'var(--color-error-3)',
        'error-7': 'var(--color-error-7)',
        'error-9': 'var(--color-error-9)',
        'error-11': 'var(--color-error-11)',
        'error-fg': 'var(--color-error-fg)',
        'success-3': 'var(--color-success-3)',
        'success-7': 'var(--color-success-7)',
        'success-9': 'var(--color-success-9)',
        'success-11': 'var(--color-success-11)',
        'success-fg': 'var(--color-success-fg)',
        'warning-3': 'var(--color-warning-3)',
        'warning-7': 'var(--color-warning-7)',
        'warning-9': 'var(--color-warning-9)',
        'warning-11': 'var(--color-warning-11)',
        'warning-fg': 'var(--color-warning-fg)',
        'info-3': 'var(--color-info-3)',
        'info-7': 'var(--color-info-7)',
        'info-9': 'var(--color-info-9)',
        'info-11': 'var(--color-info-11)',
        'info-fg': 'var(--color-info-fg)',

        // ═══ NEW: Category (step subsets) ═══
        'category-teal-3': 'var(--color-category-teal-3)',
        'category-teal-7': 'var(--color-category-teal-7)',
        'category-teal-9': 'var(--color-category-teal-9)',
        'category-teal-11': 'var(--color-category-teal-11)',
        'category-amber-3': 'var(--color-category-amber-3)',
        'category-amber-7': 'var(--color-category-amber-7)',
        'category-amber-9': 'var(--color-category-amber-9)',
        'category-amber-11': 'var(--color-category-amber-11)',
        'category-slate-3': 'var(--color-category-slate-3)',
        'category-slate-7': 'var(--color-category-slate-7)',
        'category-slate-9': 'var(--color-category-slate-9)',
        'category-slate-11': 'var(--color-category-slate-11)',
        'category-indigo-3': 'var(--color-category-indigo-3)',
        'category-indigo-7': 'var(--color-category-indigo-7)',
        'category-indigo-9': 'var(--color-category-indigo-9)',
        'category-indigo-11': 'var(--color-category-indigo-11)',
        'category-cyan-3': 'var(--color-category-cyan-3)',
        'category-cyan-7': 'var(--color-category-cyan-7)',
        'category-cyan-9': 'var(--color-category-cyan-9)',
        'category-cyan-11': 'var(--color-category-cyan-11)',
        'category-orange-3': 'var(--color-category-orange-3)',
        'category-orange-7': 'var(--color-category-orange-7)',
        'category-orange-9': 'var(--color-category-orange-9)',
        'category-orange-11': 'var(--color-category-orange-11)',
        'category-emerald-3': 'var(--color-category-emerald-3)',
        'category-emerald-7': 'var(--color-category-emerald-7)',
        'category-emerald-9': 'var(--color-category-emerald-9)',
        'category-emerald-11': 'var(--color-category-emerald-11)',

        // ═══ Utility tokens (not step-based) ═══
        overlay: 'var(--color-overlay)',
        disabled: 'var(--color-disabled)',
        'skeleton-base': 'var(--color-skeleton-base)',
        'skeleton-shimmer': 'var(--color-skeleton-shimmer)',
        'inset-glow': 'var(--color-inset-glow)',
        'inset-glow-strong': 'var(--color-inset-glow-strong)',
        'inset-glow-subtle': 'var(--color-inset-glow-subtle)',
        'surface-overlay-light': 'var(--color-surface-overlay-light)',
        'surface-overlay-dark': 'var(--color-surface-overlay-dark)',
        'text-shadow': 'var(--color-text-shadow)',
        'chart-1': 'var(--chart-1)',
        'chart-2': 'var(--chart-2)',
        'chart-3': 'var(--chart-3)',
        'chart-4': 'var(--chart-4)',
        'chart-5': 'var(--chart-5)',
        'chart-6': 'var(--chart-6)',
        'chart-7': 'var(--chart-7)',
        'chart-8': 'var(--chart-8)',
      },
      keyframes: {
        // ── Radix-coupled: height animation using Radix CSS variables ──
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'collapsible-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-collapsible-content-height)' },
        },
        'collapsible-up': {
          from: { height: 'var(--radix-collapsible-content-height)' },
          to: { height: '0' },
        },
        // ── Kept: CSS-only animations not yet migrated to Framer Motion ──
        'progress-indeterminate': {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(250%)' },
        },
        'skeleton-shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'caret-blink': {
          '0%,70%,100%': { opacity: '1' },
          '20%,50%': { opacity: '0' },
        },
        'timer-bar': {
          '0%': { transform: 'scaleX(1)' },
          '100%': { transform: 'scaleX(0)' },
        },
      },
      animation: {
        // ── Radix-coupled height animations ──
        'accordion-down': 'accordion-down 200ms ease-out',
        'accordion-up': 'accordion-up 200ms ease-out',
        'collapsible-down': 'collapsible-down 200ms ease-out',
        'collapsible-up': 'collapsible-up 200ms ease-out',
        // ── CSS-only animations ──
        'progress-indeterminate':
          'progress-indeterminate var(--duration-slow-02) var(--ease-productive-standard) infinite',
        'skeleton-shimmer':
          'skeleton-shimmer var(--duration-slow-02) var(--ease-linear) infinite',
        'caret-blink': 'caret-blink 1.25s ease-out infinite',
        'timer-bar': 'timer-bar linear forwards',
      },
      backgroundImage: {
        'gradient-brand': 'var(--gradient-brand-light)',
        'gradient-brand-dark': 'var(--gradient-brand-dark)',
      },
      boxShadow: {
        '01': 'var(--shadow-01)',
        '02': 'var(--shadow-02)',
        '03': 'var(--shadow-03)',
        '04': 'var(--shadow-04)',
        '05': 'var(--shadow-05)',
        brand: 'var(--shadow-brand)',
      },
      transitionDuration: {
        instant: 'var(--duration-instant)',
        'fast-01': 'var(--duration-fast-01)',
        'fast-02': 'var(--duration-fast-02)',
        'moderate-01': 'var(--duration-moderate-01)',
        'moderate-02': 'var(--duration-moderate-02)',
        'slow-01': 'var(--duration-slow-01)',
        'slow-02': 'var(--duration-slow-02)',
      },
      transitionTimingFunction: {
        'productive-standard': 'var(--ease-productive-standard)',
        'productive-entrance': 'var(--ease-productive-entrance)',
        'productive-exit': 'var(--ease-productive-exit)',
        'expressive-standard': 'var(--ease-expressive-standard)',
        'expressive-entrance': 'var(--ease-expressive-entrance)',
        'expressive-exit': 'var(--ease-expressive-exit)',
        bounce: 'var(--ease-bounce)',
        linear: 'var(--ease-linear)',
      },
      zIndex: {
        base: 'var(--z-base)',
        raised: 'var(--z-raised)',
        dropdown: 'var(--z-dropdown)',
        sticky: 'var(--z-sticky)',
        overlay: 'var(--z-overlay)',
        modal: 'var(--z-modal)',
        popover: 'var(--z-popover)',
        toast: 'var(--z-toast)',
        tooltip: 'var(--z-tooltip)',
      },
    },
  },
  plugins: [],
}

export default preset
