import type { Config } from 'tailwindcss'

const preset: Partial<Config> = {
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-sans)', 'system-ui', 'sans-serif'],
        display: ['var(--font-display)', 'system-ui', 'sans-serif'],
        body: ['var(--font-body)', 'sans-serif'],
        accent: ['var(--font-body)', 'sans-serif'],
        mono: ['var(--font-mono)', 'monospace'],
      },
      borderRadius: {
        'ds-sm': 'var(--radius-sm)',
        'ds-default': 'var(--radius-default)',
        'ds-md': 'var(--radius-md)',
        'ds-lg': 'var(--radius-lg)',
        'ds-xl': 'var(--radius-xl)',
        'ds-2xl': 'var(--radius-2xl)',
        'ds-full': 'var(--radius-full)',
      },
      spacing: {
        'ds-01': 'var(--spacing-01)',
        'ds-02': 'var(--spacing-02)',
        'ds-02b': 'var(--spacing-02b)',
        'ds-03': 'var(--spacing-03)',
        'ds-04': 'var(--spacing-04)',
        'ds-05': 'var(--spacing-05)',
        'ds-05b': 'var(--spacing-05b)',
        'ds-06': 'var(--spacing-06)',
        'ds-07': 'var(--spacing-07)',
        'ds-08': 'var(--spacing-08)',
        'ds-09': 'var(--spacing-09)',
        'ds-10': 'var(--spacing-10)',
        'ds-11': 'var(--spacing-11)',
        'ds-12': 'var(--spacing-12)',
        'ds-13': 'var(--spacing-13)',
      },
      width: {
        'ds-xs': 'var(--size-xs)',
        'ds-sm': 'var(--size-sm)',
        'ds-md': 'var(--size-md)',
        'ds-lg': 'var(--size-lg)',
        'ds-xl': 'var(--size-xl)',
        'ico-sm': 'var(--icon-sm)',
        'ico-md': 'var(--icon-md)',
        'ico-lg': 'var(--icon-lg)',
        'ico-xl': 'var(--icon-xl)',
      },
      height: {
        'ds-xs': 'var(--size-xs)',
        'ds-sm': 'var(--size-sm)',
        'ds-md': 'var(--size-md)',
        'ds-lg': 'var(--size-lg)',
        'ds-xl': 'var(--size-xl)',
        'ico-sm': 'var(--icon-sm)',
        'ico-md': 'var(--icon-md)',
        'ico-lg': 'var(--icon-lg)',
        'ico-xl': 'var(--icon-xl)',
      },
      minHeight: {
        'ds-xs': 'var(--size-xs)',
        'ds-sm': 'var(--size-sm)',
        'ds-md': 'var(--size-md)',
        'ds-lg': 'var(--size-lg)',
        'ds-xl': 'var(--size-xl)',
      },
      colors: {
        'text-interactive': 'var(--color-text-interactive)',
        interactive: 'var(--color-interactive)',
        'interactive-hover': 'var(--color-interactive-hover)',
        'interactive-active': 'var(--color-interactive-active)',
        'interactive-selected': 'var(--color-interactive-selected)',
        'interactive-subtle': 'var(--color-interactive-subtle)',
        accent: 'var(--color-accent)',
        'accent-hover': 'var(--color-accent-hover)',
        'accent-subtle': 'var(--color-accent-subtle)',
        background: 'var(--color-background)',
        'layer-01': 'var(--color-layer-01)',
        'layer-02': 'var(--color-layer-02)',
        'layer-03': 'var(--color-layer-03)',
        overlay: 'var(--color-overlay)',
        field: 'var(--color-field)',
        'field-hover': 'var(--color-field-hover)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-tertiary': 'var(--color-text-tertiary)',
        'text-placeholder': 'var(--color-text-placeholder)',
        'text-helper': 'var(--color-text-helper)',
        'text-disabled': 'var(--color-text-disabled)',
        'text-error': 'var(--color-text-error)',
        'text-success': 'var(--color-text-success)',
        'text-warning': 'var(--color-text-warning)',
        'text-link': 'var(--color-text-link)',
        'text-on-color': 'var(--color-text-on-color)',
        'text-inverse': 'var(--color-text-inverse)',
        'text-brand': 'var(--color-text-brand)',
        'icon-primary': 'var(--color-icon-primary)',
        'icon-secondary': 'var(--color-icon-secondary)',
        'icon-disabled': 'var(--color-icon-disabled)',
        'icon-on-color': 'var(--color-icon-on-color)',
        'icon-interactive': 'var(--color-icon-interactive)',
        border: 'var(--color-border-default)',
        'border-subtle': 'var(--color-border-subtle)',
        'border-strong': 'var(--color-border-strong)',
        'border-interactive': 'var(--color-border-interactive)',
        'border-disabled': 'var(--color-border-disabled)',
        'border-error': 'var(--color-border-error)',
        'border-success': 'var(--color-border-success)',
        'border-warning': 'var(--color-border-warning)',
        focus: 'var(--color-focus)',
        success: 'var(--color-success)',
        'success-surface': 'var(--color-success-surface)',
        error: 'var(--color-error)',
        'error-surface': 'var(--color-error-surface)',
        warning: 'var(--color-warning)',
        'warning-surface': 'var(--color-warning-surface)',
        info: 'var(--color-info)',
        'info-surface': 'var(--color-info-surface)',
        'skeleton-base': 'var(--color-skeleton-base)',
        'skeleton-shimmer': 'var(--color-skeleton-shimmer)',
        'tag-neutral-bg': 'var(--color-tag-neutral-bg)',
        'tag-neutral-text': 'var(--color-tag-neutral-text)',
        'tag-blue-bg': 'var(--color-tag-blue-bg)',
        'tag-blue-text': 'var(--color-tag-blue-text)',
        'tag-green-bg': 'var(--color-tag-green-bg)',
        'tag-green-text': 'var(--color-tag-green-text)',
        'tag-red-bg': 'var(--color-tag-red-bg)',
        'tag-red-text': 'var(--color-tag-red-text)',
        'tag-yellow-bg': 'var(--color-tag-yellow-bg)',
        'tag-yellow-text': 'var(--color-tag-yellow-text)',
        'tag-magenta-bg': 'var(--color-tag-magenta-bg)',
        'tag-magenta-text': 'var(--color-tag-magenta-text)',
        'tag-purple-bg': 'var(--color-tag-purple-bg)',
        'tag-purple-text': 'var(--color-tag-purple-text)',
      },
      keyframes: {
        ripple: {
          '0%': { transform: 'translate(-50%, -50%) scale(0)', opacity: '1' },
          '100%': { transform: 'translate(-50%, -50%) scale(4)', opacity: '0' },
        },
        shake: {
          '0%': { transform: 'translateX(0)' },
          '10%': { transform: 'translateX(-3px)' },
          '20%': { transform: 'translateX(3px)' },
          '30%': { transform: 'translateX(-8px)' },
          '40%': { transform: 'translateX(8px)' },
          '50%': { transform: 'translateX(-5px)' },
          '60%': { transform: 'translateX(3px)' },
          '70%, 100%': { transform: 'translateX(0)' },
        },
      },
      animation: {
        ripple: 'ripple 0.6s linear',
        'ripple-icon': 'ripple 300ms linear forwards',
        shake: 'shake 1s ease-in infinite',
      },
      backgroundImage: {
        'gradient-brand': 'var(--gradient-brand-light)',
        'gradient-brand-dark': 'var(--gradient-brand-dark)',
      },
      boxShadow: {
        '01': 'var(--shadow-01)',
        '02': 'var(--shadow-02)',
        '03': 'var(--shadow-03)',
        '04': 'var(--shadow-04)',
        '05': 'var(--shadow-05)',
        brand: 'var(--shadow-brand)',
      },
      transitionDuration: {
        instant: 'var(--duration-instant)',
        fast: 'var(--duration-fast)',
        moderate: 'var(--duration-moderate)',
        slow: 'var(--duration-slow)',
        medium: 'var(--duration-medium)',
        deliberate: 'var(--duration-deliberate)',
      },
      transitionTimingFunction: {
        standard: 'var(--ease-standard)',
        entrance: 'var(--ease-entrance)',
        exit: 'var(--ease-exit)',
        bounce: 'var(--ease-bounce)',
        linear: 'var(--ease-linear)',
      },
      zIndex: {
        base: 'var(--z-base)',
        raised: 'var(--z-raised)',
        dropdown: 'var(--z-dropdown)',
        sticky: 'var(--z-sticky)',
        overlay: 'var(--z-overlay)',
        modal: 'var(--z-modal)',
        toast: 'var(--z-toast)',
        tooltip: 'var(--z-tooltip)',
      },
    },
  },
}

export default preset
